import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { ToastContainer } from 'react-toastify';
import { cookies } from "next/headers";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function getCookies() {
  return cookies().get("login_token")?.value;
  
}

export default function RootLayout({ children }) {
  let token=getCookies(); 
  console.log(token)// Call the function here to log the cookie

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar value={token} />
        <ToastContainer />
        {children}
        <Footer />
      </body>
    </html>
  );
}
